### ISSUE TITLE
Duplicate entries created by sync_service

### ISSUE THREAD

**Issue by mageo** [stayhomech/stayhomech#49]
I restarted several times the project on my local environment with Docker and it seems that the sync_service is pushing all the same entries every time it restarts (or gets them from the nodefetch container).

Can you check that the deduplication is working correctly ?

**Comment by pavax** [comment]
I have not yet implemented an duplication/checksum check in the sync-service. Every time I receive an request I simply merge it with an (potential) existing request from the stayhome-api or create a one from scratch. The sync-service also calculates the checksum (based on certain fields) and sends that one as well to the stayhome-api.

I though that I need to send all the incoming requests to the stay-home api  (no filter based on the checksum) - so that the stayhome-api can handle that (for example to decide to update a request, refresh the entries TTL etc).

I can add a check in the syn-service and only POST a Request if the checksum has changed or the Request is new (=> not known to the stahome-api yet) - but then we need to think about the deletion/TTL on your side...


... also the sync-service is still stateless I thinkt it must be the nodefetch's (scheduler) that runs regurarly or on startup and send it's data to the sync-servie

**Comment by mageo** [comment]
Here is how I see the relation between the sync-service and the web-api : 

* At startup, the sync-service fetch all existing requests from the web-api in order to have an initial state.
* When the the sync-service receives a "new" requests, it has to compute the checksum of this request and see if it already exists in its state.
  * If the request already exists, the sync-state must perform an update of the request in the web-api in order to update the TTL. The checksum field must not change, the TTL field must be updated. (PUT on /requests/<request_uuid>/)
  * If the request does not exists, the sync-state must create the request on the web-api. (POST on /requests/)
  * If the request changed, the sync-state must update the request in the web-api. The new checksum must be given and the TTL field must be updated. (PUT on /requests/<request_uuid>/)
* If the sync-service does not receive the external request for an existing entry in its state after the duration of the TTL, the entry can be deleted in its state. No need to send a DELETE to the web-api, the deletion will be automatic.

**Comment by pavax** [comment]
I guess I found at least one issue

* the sync-service send a field called: check**S**um instead of checksum 
* also I was not using the PUT api to update it (haven't seen that this one is available) -> will try

**Comment by mageo** [comment]
Yeap, this will not help :-)

Just to be 100% clear : the checksum field is not used by the web-api to check the uniqueness of the request. It is only used to detect a change in an existing request. The uniqueness is warranted by the uuid field of the request that is generated by the web-api at creation.

**Comment by mageo** [comment]
Also remember that there's a field called "source_uuid" that you can use to store your own unique key for a request, for example if the external source provides an ID.

Of course if you don't get an ID from the external source you have to find another way ;-)

**Comment by pavax** [comment]
with regards to https://github.com/stayhomech/stayhomech/pull/54

## Some clarifications

* checksum fields (all fields except): handled, deleted, creation, update, ttl, uuid
* in the past i used the TTL approach as an expiryDate. In our case the datasource provider sends as a TTL of 3 Days -> sync-service receives it and calculates ```expiryDate = now() + 3 days```. As long as we still receive that entry, the expiryDate will always get extended.  Then there is gonna be a cleanup-scheduler, that deletes the entries that have expired . This can either be in the sync-service (would become statefull but is absolutely not a big deal/effort for me)  or in the web-api backend

## Example seqences

### First run at 2020-03-24
1. sync-service receives a request (```source_id: test-001```) from an integrator 
2. sync-service fetches an potential existing request from the web-api (find by source_uuid= test-001)
4. sync-service builds the ```checksum: 7777``` and ```TTL: 3d``` / ```expiryDate: 2020-03-27```
3. since sync-service hos not yet found an existing request in the web-api we create/POST it
4. web-api creates a new request

### Next run (same entry and no change in fields) at 2020-03-25
1. sync-service receives a request (```source_id: test-001```) from an integrator 
2. sync-service fetches an potential existing request from the web-api (find by ```source_uuid= test-001```)
4. sync-service builds the ```checksum: 7777``` and ```TTL: 3d``` / ```expiryDate: 2020-03-28```
3. since sync-service has found an existing request in the web-api we update/PUT it
4. web-api checks that the checksums are equal -> nothing at web-api side

### Next run (same entry but change in fields) at 2020-03-26
1. sync-service receives a request (```source_id: test-001```) from an integrator 
2. sync-service fetches an potential existing request from the web-api (find by ```source_uuid= test-001```)
4. sync-service builds the ```checksum: 6666``` and ```TTL: 3d``` ```expiryDate: 2020-03-29```
3. sync-service has found an existing request in the web-api we update-> PUT it
4. web-api checks that the checksums are NOT equal -> requests a manual update

### source_id: test-001 gets deleted in the datasource (eg. derBund)

### Next run at 2020-03-27
1.  sync-service does not receive that entry from the datasource-integrator-app anymore -> nothing happens in the sync-service

### Scheduler at 2020-03-29
* I'd assume the web-api backend ~~(or sync-service)~~ deletes that request since it has reached it's ```expiryDate: 2020-03-29``` (as it got not extended anymore)

**Comment by mageo** [comment]
Sounds good to me !

**Comment by pavax** [comment]
@mageo so shall I make the sync-service statefull and send you a delete request for an request that hasn't been fetched/seen since XXX TTL times?

**Comment by pavax** [comment]
We decided that the web-api is going to handle the TTL/expiry check
